### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter'

### ISSUE THREAD

**Issue by brylie** [synw/django-chartflo-demo#1]
When running the installation instructions from README, at the `python3 manage.py migrate` step, I get the following error:

```
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by brylie** [comment]
Here is the full stack trace:

```
$ python3 manage.py migrate
INFO:matplotlib.font_manager:font search path ['/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/ttf', '/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/afm', '/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/matplotlib/mpl-data/fonts/pdfcorefonts']
INFO:matplotlib.font_manager:generated new fontManager
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
    django.setup()
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/home/brylie/code/Django/chartflo/django-chartflo-demo/timeseries/apps.py", line 9, in ready
    from .signals import serie_create_update, serie_delete
  File "/home/brylie/code/Django/chartflo/django-chartflo-demo/timeseries/signals.py", line 5, in <module>
    from .pipeline import generate
  File "/home/brylie/code/Django/chartflo/django-chartflo-demo/timeseries/pipeline.py", line 4, in <module>
    from dataswim import ds
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/dataswim/__init__.py", line 5, in <module>
    from .charts import Plot
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/dataswim/charts/__init__.py", line 5, in <module>
    from .seaborn import Seaborn
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/dataswim/charts/seaborn.py", line 1, in <module>
    import seaborn as sns
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/seaborn/__init__.py", line 6, in <module>
    from .rcmod import *
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/seaborn/rcmod.py", line 5, in <module>
    from . import palettes, _orig_rc_params
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/seaborn/palettes.py", line 12, in <module>
    from .utils import desaturate, set_hls_values, get_color_cycle
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/seaborn/utils.py", line 11, in <module>
    import matplotlib.pyplot as plt
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/matplotlib/backends/backend_tkagg.py", line 4, in <module>
    from . import tkagg  # Paint image to Tk photo blitter extension.
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/matplotlib/backends/tkagg.py", line 5, in <module>
    from six.moves import tkinter as Tk
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/six.py", line 92, in __get__
    result = self._resolve()
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/home/brylie/code/Django/chartflo/lib/python3.6/site-packages/six.py", line 82, in _import_module
    __import__(name)
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by brylie** [comment]
I tried to import `tkinter` directly in a Python REPL and got the same error:

```
$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tkinter'
>>> 
```

**Comment by brylie** [comment]
On Kubuntu 18.04, installing the `python3-tk` package fixed the issue:

```
sudo apt install python3-tk
```

**Comment by synw** [comment]
This is weird. It looks like Matplotlib needs this at some point. I should change the default backend, to avoid this problem according to [this answer](https://stackoverflow.com/a/49988926):

```
import matplotlib
matplotlib.use('agg')
```

Thanks for reporting

**Comment by synw** [comment]
The Matplotlib backend has been changed so this should not happen anymore
